function ims = renderDerivImageScenes(sigmaT, sigmaS, func,...
												sigmaTSingle, sigmaSSingle, funcSingle,...
												theta, sceneSet, rendererSet)

numScenes = length(sceneSet);
assert(length(rendererSet) == numScenes);
ims = cell(numScenes, 1);
parfor iterScene = 1:numScenes,
	ims{iterScene} = renderDerivImage(sigmaT, sigmaS, func,...
												sigmaTSingle, sigmaSSingle, funcSingle, theta,...
												sceneSet(iterScene), rendererSet(iterScene));
end;
